/**
  ******************************************************************************
  * @file    plc_instruction.h
  * @author  lixianyu
  * @version V0.0.1
  * @date    2019-03-19
  * @brief   PLC 指令操作码定义
  ******************************************************************************
  */
#ifndef __PLC_INSTRUCTION_H
#define __PLC_INSTRUCTION_H

/*------------------------------------------------------------------------------
* 简单指令
*-----------------------------------------------------------------------------*/
enum __PLC_SIMPLE_INS {
    SI_LD_X         = 0x10,
    SI_LD_Y,
    SI_LD_C,
    SI_LD_T,
    SI_LD_SM,
    SI_LD_M         = 0x15,
    SI_LD_S,
    SI_LD_LM,
    SI_LD_X_EXT,
    SI_LD_Y_EXT,
    SI_LD_C_EXT,
    SI_LD_T_EXT,
    SI_LD_SM_EXT    = 0x1C,
    SI_LD_M_EXT     = 0x1D,
    SI_LD_S_EXT     = 0x1E,
    SI_LDI_X        = 0x20,
    SI_LDI_Y,
    SI_LDI_C,
    SI_LDI_T,
    SI_LDI_SM,
    SI_LDI_M,
    SI_LDI_S,
    SI_LDI_LM,
    SI_LDI_X_EXT,
    SI_LDI_Y_EXT,
    SI_LDI_C_EXT,
    SI_LDI_T_EXT,
    SI_LDI_SM_EXT,
    SI_LDI_M_EXT,
    SI_LDI_S_EXT    = 0x2E,
    SI_AND_X        = 0x30,
    SI_AND_Y,
    SI_AND_C,
    SI_AND_T,
    SI_AND_SM,
    SI_AND_M,
    SI_AND_S,
    SI_AND_LM,
    SI_AND_X_EXT,
    SI_AND_Y_EXT,
    SI_AND_C_EXT,
    SI_AND_T_EXT,
    SI_AND_SM_EXT,
    SI_AND_M_EXT,
    SI_AND_S_EXT    = 0x3E,
    SI_ANI_X        = 0x40,
    SI_ANI_Y,
    SI_ANI_C,
    SI_ANI_T,
    SI_ANI_SM,
    SI_ANI_M,
    SI_ANI_S,
    SI_ANI_LM,
    SI_ANI_X_EXT,
    SI_ANI_Y_EXT,
    SI_ANI_C_EXT,
    SI_ANI_T_EXT,
    SI_ANI_SM_EXT,
    SI_ANI_M_EXT,
    SI_ANI_S_EXT    = 0x4E,
    SI_OR_X        = 0x50,
    SI_OR_Y,
    SI_OR_C,
    SI_OR_T,
    SI_OR_SM,
    SI_OR_M,
    SI_OR_S,
    SI_OR_LM,
    SI_OR_X_EXT,
    SI_OR_Y_EXT,
    SI_OR_C_EXT,
    SI_OR_T_EXT,
    SI_OR_SM_EXT,
    SI_OR_M_EXT,
    SI_OR_S_EXT    = 0x5E,
    SI_ORI_X        = 0x60,
    SI_ORI_Y,
    SI_ORI_C,
    SI_ORI_T,
    SI_ORI_SM,
    SI_ORI_M,
    SI_ORI_S,
    SI_ORI_LM,
    SI_ORI_X_EXT,
    SI_ORI_Y_EXT,
    SI_ORI_C_EXT,
    SI_ORI_T_EXT,
    SI_ORI_SM_EXT,
    SI_ORI_M_EXT,
    SI_ORI_S_EXT    = 0x6E,
    SI_OUT_Y        = 0x71,
    SI_OUT_SM       = 0x74,
    SI_OUT_M,
    SI_OUT_LM       = 0x77,
    SI_OUT_Y_EXT    = 0x79,
    SI_OUT_SM_EXT   = 0x7C,
    SI_OUT_M_EXT,
    SI_SET_Y        = 0x81,
    SI_SET_SM       = 0x84,
    SI_SET_M,
    SI_SET_LM       = 0x87,
    SI_SET_Y_EXT    = 0x89,
    SI_SET_SM_EXT   = 0x8C,
    SI_SET_M_EXT,
    SI_RST_Y        = 0x91,
    SI_RST_SM       = 0x94,
    SI_RST_M,
    SI_RST_LM       = 0x97,
    SI_RST_Y_EXT    = 0x99,
    SI_RST_SM_EXT   = 0x9C,
    SI_RST_M_EXT,
    SI_INV          = 0xA0,
    SI_ANB,
    SI_ORB,
    SI_MPS,
    SI_MRD,
    SI_MPP,
    SI_NOP,
    SI_EU,
    SI_ED           = 0xA8,

    SI_LDP           = 0xB0,
    SI_LDF,
    SI_ANDP,
    SI_ANDF,
    SI_ORP,
    SI_ORF,
    SI_PLP,
    SI_PLF,


    SI_MAX_INS
};

/*------------------------------------------------------------------------------
* 复杂指令
*-----------------------------------------------------------------------------*/
enum __PLC_COMPLEX_INS {
    CI_LBL          = 0xF000,
    CI_SBR          = 0xF001,
    CI_INTR,
    CI_LD_LM,
    CI_LDI_LM,
    CI_AND_LM,
    CI_ANI_LM,
    CI_OR_LM,
    CI_ORI_LM,
    CI_OUT_LM,
    CI_SET_LM,
    CI_RST_LM       = 0xF00B,
    CI_STL          = 0xF00E,
    CI_RST_S        = 0xF00F,
    CI_SET_S        = 0xF010,
    CI_OUT_S,
    CI_RET          = 0xF012,
    CI_TON          = 0xF014,
    CI_TOF,
    CI_TONR,
    CI_RST_T,
    CI_DCNT,
    CI_CTU,
    CI_CTR          = 0xF01A,
    CI_RST_C        = 0xF01B,
    CI_MC,
    CI_MCR,
    CI_CJ,
    CI_FOR,
    CI_NEXT         = 0xF020,
    CI_CALL,
    CI_CSRET,
    CI_SRET         = 0xF023,
    CI_CIRET,
    CI_IRET,
    CI_EI,
    CI_DI,
    CI_STOP,
    CI_WDT          = 0xF029,
    CI_CFEND,
    CI_FEND         = 0xF02B,
    CI_MOV          = 0xF02D,
    CI_DMOV         = 0xF02E,
    CI_BMOV         = 0xF02F,
    CI_FMOV         = 0xF031,
    CI_DFMOV,
    CI_SWAP,
    CI_XCH          = 0xF035,
    CI_DXCH,
    CI_PUSH,
    CI_WSFL         = 0xF038,
    CI_LDE,
    CI_LDG,
    CI_LDL,
    CI_LDNE,
    CI_LDLE,
    CI_LDGE,
    CI_ANDE         = 0xF03F,
    CI_ANDG         = 0xF040,
    CI_ANDL,
    CI_ANDNE,
    CI_ANDLE,
    CI_ANDGE,
    CI_ORE,
    CI_ORG,
    CI_ORL,
    CI_ORNE,
    CI_ORLE,
    CI_ORGE,
    CI_LDDE,
    CI_LDDG,
    CI_LDDL,
    CI_LDDNE,
    CI_LDDLE        = 0xF04F,
    CI_LDDGE        = 0xF050,
    CI_ANDDE,
    CI_ANDDG,
    CI_ANDDL,
    CI_ANDDNE,
    CI_ANDDLE,
    CI_ANDDGE,
    CI_ORDE,
    CI_ORDG,
    CI_ORDL,
    CI_ORDNE,
    CI_ORDLE,
    CI_ORDGE,
    CI_LDRE,
    CI_LDRG,
    CI_LDRL         = 0xF05F,
    CI_LDRNE        = 0xF060,
    CI_LDRLE,
    CI_LDRGE,
    CI_ANDRE,
    CI_ANDRG,
    CI_ANDRL,
    CI_ANDRNE,
    CI_ANDRLE,
    CI_ANDRGE,
    CI_ORRE,
    CI_ORRG,
    CI_ORRL,
    CI_ORRNE,
    CI_ORRLE,
    CI_ORRGE,
    CI_ADD          = 0xF06F,
    CI_SUB          = 0xF070,
    CI_MUL,
    CI_DIV,
    CI_SQT,
    CI_INC,
    CI_DEC,
    CI_VABS,
    CI_NEG          = 0xF077,
    CI_DADD         = 0xF079,
    CI_DSUB,
    CI_DMUL,
    CI_DDIV,
    CI_DSQT,
    CI_DINC,
    CI_DDEC         = 0xF07F,
    CI_DVABS        = 0xF080,
    CI_DNEG,
    CI_RADD         = 0xF083,
    CI_RSUB,
    CI_RMUL,
    CI_RDIV,
    CI_RSQT         = 0xF087,
    CI_SIN,
    CI_COS,
    CI_TAN,
    CI_LN,
    CI_EXP,
    CI_RNEG         = 0xF08D,
    CI_POWER,
    CI_RVABS        = 0xF08F,
    CI_WAND         = 0xF090,
    CI_WOR,
    CI_WXOR,
    CI_WINV,
    CI_DWAND,
    CI_DWOR,
    CI_DWXOR,
    CI_DWINV,
    CI_ROR,
    CI_ROL,
    CI_RCR,
    CI_RCL,
    CI_DROR,
    CI_DROL,
    CI_DRCR,
    CI_DRCL         = 0xF09F,
    CI_SHR          = 0xF0A0,
    CI_SHL,
    CI_DSHR,
    CI_DSHL,
    CI_SFTR,
    CI_SFTL         = 0xF0A5,
    CI_FLT          = 0xF0A8,
    CI_DFLT,
    CI_INT,
    CI_DINT,
    CI_BCD,
    CI_DBCD,
    CI_BIN,
    CI_DBIN         = 0xF0AF,
    CI_GRY          = 0xF0B0,
    CI_DGRY,
    CI_GBIN,
    CI_DGBIN,
    CI_SEG,
    CI_ASC,
    CI_ITA,
    CI_ATI          = 0xF0B7,
    CI_PR,
    CI_FROM         = 0xF0BB,
    CI_TO,
    CI_EROMWR,
    CI_REF,
    CI_REFF         = 0xF0BF,
    CI_DECO         = 0xF0C0,
    CI_ENCO,
    CI_BITS,
    CI_ZRST,
    CI_ZSET         = 0xF0C4,
    CI_PID,
    CI_XMT,
    CI_TRD,
    CI_TWR,
    CI_TADD,
    CI_TSUB,
    CI_FIFO         = 0xF0CB,
    CI_LIFO,
    CI_HOUR         = 0xF0CE,
    CI_BLD          = 0xF0D2,
    CI_BLDI,
    CI_BAND,
    CI_BANDI,
    CI_BOR,
    CI_BORI         = 0xF0D7,
    CI_DBITS        = 0xF0DB,
    CI_BON          = 0xF0DE,
    CI_DHSCS        = 0xF0DF,
    CI_DHSCR        = 0xF0E0,
    CI_DHSZ,
    CI_DHST,
    CI_DHSP,
    CI_PLSY,
    CI_PLSR,
    CI_PWM,
    CI_SPD,
    CI_HCNT,
    CI_DFROM        = 0xF0E9,
    CI_DTO,
    CI_DHSCI        = 0xF0EB,
    CI_BSET         = 0xF0EC,
    CI_BRST,
    CI_WSFR         = 0xF0EF,
    CI_ITD          = 0xF0F0,
    CI_DTI,
    CI_BOUT,
    CI_RMOV         = 0xF0F3,
    CI_RCV,
    CI_VRRD,
    CI_MODBUS       = 0xF0F6,
    CI_DIAL         = 0xF0F7,
    CI_HANGUP,
    CI_SUM,
    CI_DSUM,
    CI_RSUM,
    CI_DCMPE,
    CI_DCMPG,
    CI_DCMPL,
    CI_DCMPNE       = 0xF0FF,
    CI_DCMPLE       = 0xF100,
    CI_DCMPGE,
    CI_TCMPE,
    CI_TCMPG,
    CI_TCMPL,
    CI_TCMPNE,
    CI_TCMPLE,
    CI_TCMPGE,
    CI_RAMP,
    CI_HACKLE,
    CI_TRIANGLE,
    CI_TMON,
    CI_CCITT,
    CI_CRC16,
    CI_LRC          = 0xF10E,
    CI_ABS          = 0xF130,
    CI_ZRN,
    CI_PLSV,
    CI_DRVI,
    CI_DRVA,
    CI_PLS          = 0xF135,
    CI_DSZR,
    CI_PLSB         = 0xF138,
    CI_EVFWD        = 0xF140,
    CI_EVREV,
    CI_EVDFWD,
    CI_EVDREV,
    CI_EVSTOP,
    CI_EVFRQ,
    CI_EVWRT,
    CI_EVRDST,
    CI_EVRD         = 0xF148,
    CI_CANXMT,
    CI_CANRCV,
    CI_CANMXMT      = 0xF14D,
    CI_LCNV         = 0xF150,
    CI_CMP,
    CI_LCMP,
    CI_RCMP         = 0xF153,
    CI_ALT,
    CI_ABSD,
    CI_DABSD        = 0xF156,
    CI_MODRW        = 0xF160,
    CI_ASIN         = 0xF170,
    CI_ACOS,
    CI_ATAN         = 0xF172,
    CI_MTR,
    CI_RLCNV        = 0xF174,

    CI_TCP_CONN     = 0xF180,
    CI_TCP_XMT      = 0xF181,
    CI_TCP_RCV      = 0xF182,
    CI_TCP_PING     = 0xF183,

    CI_MODLINK      = 0xF19C,
    CI_MBCCONN      = 0xF19D,
    CI_MODTCPLINK   = 0xF19E,
    CI_S7TCPLINK    = 0xF19F,
    CI_LOG          = 0xF200,
    CI_RAD,
    CI_DEG          = 0xF202,
    CI_TKY          = 0xF210,
    CI_HKY          = 0xF211,
    CI_DSW          = 0xF212,
    CI_ARWS         = 0xF214,
    CI_DHSCT        = 0xF220,
    CI_DHSPI        = 0xF221,
    CI_CONTINUE     = 0xF222,
    CI_BREAK        = 0xF223,

    /*字触点*/
    CI_LD_DX_Y      = 0xF230,
    CI_LDI_DX_Y,
    CI_AND_DX_Y,
    CI_ANI_DX_Y,
    CI_OR_DX_Y,
    CI_ORI_DX_Y,
    CI_SET_DX_Y,
    CI_RST_DX_Y,
    CI_OUT_DX_Y     = 0xF238,

    CI_LIN          = 0xF240,
    CI_CW,
    CI_CCW,
    CI_DRV          = 0xF243,
    CI_MOVELINK     = 0xF245,
    CI_STOPDV,
    CI_GEARBOX,
    CI_CAMBOX       = 0xF248,
    /*数据处理*/
    CI_MEAN         = 0xF250,
    CI_WTOB         = 0xF251,
    CI_BTOW,
    CI_UNI,
    CI_DIS,
    CI_ANS,
    CI_ANR          = 0xF256,
    /*数据块处理*/
    CI_BKADD        = 0xF260,
    CI_BKSUB,
    CI_BKCMPDE,
    CI_BKCMPDG,
    CI_BKCMPDL,
    CI_BKCMPDNE,
    CI_BKCMPDLE,
    CI_BKCMPDGE     = 0xF267,
    /*数据表处理*/
    CI_LIMIT        = 0xF270,
    CI_DBAND,
    CI_ZONE,
    CI_SCL,
    CI_SER          = 0xF274,
    /*便捷指令*/
    CI_IST          = 0xF280,
    CI_INCD,
    CI_TTMR,
    CI_STMR,
    CI_ROTC,
    CI_SORT         = 0xF285,
    /*字符串处理*/
    CI_STRADD       = 0xF290,
    CI_STRLEN,
    CI_STRRIGHT,
    CI_STRLEFT,
    CI_STRMIDR,
    CI_STRMIDW,
    CI_STRINSTR,
    CI_STRMOV       = 0xF297,
    /*扩展文件寄存器*/
    CI_LOADR        = 0xF2A0,
    CI_SAVER,
    CI_INITR,
    CI_LOGR,
    CI_INITER       = 0xF2A4,
    CI_CAMTABLE     = 0xF2A5,
    CI_DRVC         = 0xF2A7,

    CI_RND          = 0xF2B0,
    CI_DUTY,
    CI_HTOS         = 0xF2C0,
    CI_STOH         = 0xF2C1,
    //CI_ECATNMT      = 0xF2D6,
    CI_ECATSDORD    = 0xF2D7,
    CI_ECATSDOWR    = 0xF2D8,
    
    CI_SWAPWORD     = 0xF2D9,

    CI_END          = 0xFFFF,
};

/*------------------------------------------------------------------------------
* 执行器调用指令解释函数返回值定义
*-----------------------------------------------------------------------------*/
enum __PLC_EXEC_CALLBACK_FLAG{
    /*主程序条件返回*/
    EXEC_FLAG_FEND  = 0x02,
    EXEC_FLAG_IRET,
    /*用户子程序条件返回*/
    EXEC_FLAG_SRET,
    EXEC_FLAG_STOP
};

#endif /*__PLC_INSTRUCTION_H*/

